language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: 27Vj2zPXKEQhFn70t0VC/DWGl0w97fnSlVX+RceeHq/tBVHHbLT74uvZYqw1EbRmVkbaQ7u9NvMrUuRhFKck3xEuPIyufl4XhNjFLl7zr4xfY5SEAXC3xN8AV96D7YOnfwuXWC+WjllO2WTgvZFg2nI3W8ZTRQG3sHkS4/lsy+s=
  app: name
  on:
    repo: TuukkaP/wadror
  run: "rake db:migrate"